[package]
name = "monero-wallet-sys"
version = "0.1.0"
authors = ["Thomas Eizinger <thomas@eizinger.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1"
autocxx = { path = "./autocxx" }

[build-dependencies]
autocxx-build = { path = "./autocxx/gen/build" }
